### ISSUE TITLE
PubSub overload drops messages

### ISSUE THREAD

**Issue by davelar** [go-mangos/mangos#178]
In using pub/sub, I got into a case in which a bunch of pubs occur with basically in a tight loop. I changed to send less messages and it resolved my problem. A delay also seems to solve the problem, but doesn't quite seem like a fix. 
I modified the pubsub example that you have and created basically a tight pub of 1000 messages. If you run the server and client, you'll see something like:

CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 0
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 1
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 2
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 3
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 4
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 5
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 6
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 7
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 8
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 9
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 10
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 11
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 12
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 13
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 14
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 15
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 16
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 17
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 18
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 19
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 20
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 21
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 22
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 23
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 24
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 25
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 26
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 27
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 28
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 29
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 30
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 31
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 32
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 33
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 34
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 35
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 36
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 37
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 38
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 39
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 40
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 41
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 42
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 43
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 44
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 45
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 46
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 47
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 48
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 49
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 50
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 51
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 52
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 53
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 54
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 55
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 56
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 57
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 58
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 59
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 60
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 61
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 62
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 63
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 64
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 65
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 66
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 67
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 68
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 69
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 70
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 71
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 72
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 73
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 74
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 75
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 76
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 77
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 78
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 79
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 80
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 81
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 82
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 83
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 84
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 85
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 86
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 87
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 88
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 89
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 90
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 91
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 92
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 93
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 94
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 95
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 96
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 97
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 98
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 99
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 100
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 101
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 102
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 103
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 104
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 105
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 106
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 107
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 108
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 109
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 110
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 111
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 112
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 113
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 114
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 115
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 116
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 117
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 118
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 119
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 120
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 121
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 122
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 123
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 124
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 125
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 126
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 127
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 128
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 129
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 130
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 131
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 132
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 133
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 134
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 135
!!!!!!!!!!MISSED MESSAGES(14)!!!!!!!!!!
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 149
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 150
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 151
!!!!!!!!!!MISSED MESSAGES(9)!!!!!!!!!!
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 160
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 161
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 162
!!!!!!!!!!MISSED MESSAGES(9)!!!!!!!!!!
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 171
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 172
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 173
!!!!!!!!!!MISSED MESSAGES(10)!!!!!!!!!!
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 183
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 184
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 185
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 186
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 187
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 188
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 189
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 190
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 191
!!!!!!!!!!MISSED MESSAGES(3)!!!!!!!!!!
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 194
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 195
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 196
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 197
!!!!!!!!!!MISSED MESSAGES(4)!!!!!!!!!!
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 201
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 202
!!!!!!!!!!MISSED MESSAGES(12)!!!!!!!!!!
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 214
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 215
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 216
!!!!!!!!!!MISSED MESSAGES(7)!!!!!!!!!!
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 223
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 224
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 225
!!!!!!!!!!MISSED MESSAGES(4)!!!!!!!!!!
CLIENT(client0): RECEIVED Mon Jan 25 14:43:07 2016 AND COUNT 229
...

File is attached. Thanks for any help. 

[pubsub_issue.go.zip](https://github.com/go-mangos/mangos/files/103850/pubsub_issue.go.zip)

**Comment by Term1nal** [comment]
Have you tried it without a TCP transport and just IPC? Vise Versa?

My guess, such a tight loop is broadcasting faster than some internal polling frequency. Perhaps you could retry your example using TCP, and even moreso, between two physical network hosts.

There has been things said about the lacking in optimization in the IPC transport. So it's possible that has something to do with it? Or even a kernel-related issue?

**Comment by Term1nal** [comment]
After some digging, perhaps maybe related to `ENOBUFS`? Essentially, the loop is could be filling up the buffer causing packets to be silently dropped? Not sure about that.

**Comment by gdamore** [comment]
That is exactly what is happening.  Pub is best effort only.  If you send too fast messages WILL drop. You need to send no faster than they can be transmitted and consumed.

**Comment by gdamore** [comment]
This isn't a bug.  Closing it.
