### ISSUE TITLE
rep server that doesn't block new Recv until it Send?

### ISSUE THREAD

**Issue by sb10** [go-mangos/mangos#187]
I have a server process that uses rep:

    sock, _ := rep.NewSocket()
    sock.AddTransport(tcp.NewTransport())
    sock.Listen(addr)
    for {
        cr, _ := sock.Recv()

        // do some time consuming thing with cr

        sock.Send(reply)
    }

I have corresponding client processes that use req:

    sock, _ := req.NewSocket()
    sock.AddTransport(tcp.NewTransport())
    sock.Dial(addr)
    sock.Send(request)
    reply, _ := sock.Recv()

That all works fine. In the scenario where many clients are all requesting something from the server, how do you make the server accept and start dealing with all their requests at once, without having to wait for the time consuming bit before looping to the next Recv()?

I tried this for the server:

    // same sock set up as before, then
    for {
        cr, _ := sock.Recv()
        
        go func() {
             // do some time consuming thing with cr
            err := sock.Send(reply)
            if err != nil {
                fmt.Println(err)
            }
        }()
    }

But it fails on that Send with:

> incorrect protocol state

Is there a way to Send() to a client after you've already Recv()d from a different client? Or is there some completely different pattern that can handle this?

**Comment by gdamore** [comment]
To handle these in parallel you have to use the raw mode. You can set this as an option on the socket. Then when you reply you have to use the same headers that you received so that mangos knows where to send the reply.  I think I built an example of this somewhere.  Let me check and I will get back to you.

**Comment by gdamore** [comment]
Yes, found it here: https://github.com/go-mangos/mangos/blob/master/examples/raw/server.go

Basically, the code above sets up raw mode, then runs concurrent servers each doing their own req/rep on the *same* shared socket.  The critical thing is that the request ID is pulled off the header, and put back, and the *rest* of the message headers are retrained from the original message.

mangos could probably use a simpler or cleaner API for this .

**Comment by sb10** [comment]
Thanks, I'll have a go with that.
