### ISSUE TITLE
ROUTER/DEALER pattern?

### ISSUE THREAD

**Issue by lostinblue** [go-mangos/mangos#196]
I'm curious if mongos impelements the ROUTER/DEALER connection design pattern? Can I use existing design patterns in mongos to emulate this? If not is there any plans to implement this?

http://zeromq.org/sandbox:dealer

**Comment by lostinblue** [comment]
I guess its called PIPELINE in nanomsg. After reviewing the code if it does not exist I will try to add it.

**Comment by mbarkhau** [comment]
Was this ever implemented?

**Comment by gdamore** [comment]
This is the REQ/REP pattern mangos and nanomsg combined with devices.  If you want more control than round robin balancing you will need to implement the logic yourself.
