### ISSUE TITLE
Add support for Named Pipes on Windows

### ISSUE THREAD

**Issue by gdamore** [go-mangos/mangos#2]
Originally: https://bitbucket.org/gdamore/mangos/issue/2  

The IPC transport only works with Unix domain sockets. While Go has no native support for Named Sockets, the libnanomsg API does. We could probably come up with something for Windows, if there was a demand.
Note that Windows users can always use the TCP transport.

**Comment by gdamore** [comment]
So the go team have declined to do this natively, but there is:

https://godoc.org/gopkg.in/natefinch/npipe.v2

We can use that for Windows.  One challenge might be making sure that libnanomsg and mangos can both interoperate over this transport.  I *think* that should be possible, but verification will be required.

**Comment by gdamore** [comment]
Having looked at Windows IPC, I'm less convinced this is a good idea.  In particular, the model for Named Pipes is a bit different, as there isn't a separate file for the connected pipe.  Additionally there is a limit of 255 instances for a given Named Pipe.  I cannot recommend Named Pipes for the usual use cases involving nanomsg.

**Comment by binary132** [comment]
Maybe this could be done just by mmap of a shared file.  I think there's a Boost IPC lib which does this on Windows.  http://www.boost.org/doc/libs/1_47_0/doc/html/interprocess/sharedmemorybetweenprocesses.html#interprocess.sharedmemorybetweenprocesses.sharedmemory

This would be a pretty awesome feature!

**Comment by gdamore** [comment]
We could certainly emulate something here -- but the problem is that nanomsg uses Windows Named Pipes.  So we need to support them in order to be compatible with nanomsg.  That said, Windows Named Pipes are a friggin' joke.

**Comment by sumito3478** [comment]
Hi, thanks for the great library.

According to MSDN, I think passing PIPE_UNLIMITED_INSTANCES to CreateNamedPipe makes the number of pipe instances unlimited:
https://msdn.microsoft.com/ja-jp/library/windows/desktop/aa365150(v=vs.85).aspx
> If this parameter is PIPE_UNLIMITED_INSTANCES, the number of pipe instances that can be created is limited only by the availability of system resources.

And nanomsg does that https://github.com/nanomsg/nanomsg/blob/69846d0bea3a9c9842fb87199d70a728aec7a299/src/aio/usock_win.inc#L529

Probably I will try to implement nanomsg-compatible IPC transport support on Windows later.

**Comment by gdamore** [comment]
Nanomsg IPC is actually pretty busted on Windows as I found out when implementing this.  It makes some very bad assumptions about reads vs. writes, which works as long as it is the other side.   It turns out that NNG makes no such assumptions.  I have a version of mangos with this capability (funded by a commercial customer) which works well, but it has to make an extra data copy to work around the ugly bugs in legacy nanomsg.
