### ISSUE TITLE
Refactoring - make Protoxxx a type

### ISSUE THREAD

**Issue by grrtrr** [go-mangos/mangos#201]
This is a simplifying enhancement: instead of maintaining protocol number (`uint16`) and name, use a dedicated `ProtocolNumber` type with a `Stringer` function.

Example:
```go
// ProtocolNumber represents the registered number associated with the protocol.
type ProtocolNumber uint16
const (
      ProtoPair      ProtocolNumber = (1 * 16)
      ProtoPub       ProtocolNumber = (2 * 16)
      // ...
      ProtoStar      ProtocolNumber = (100 * 16)
)

func (p ProtocolNumber) String() string {
    switch p {
    case ProtoPair:
          return "pair"
    case ProtoPub:
          return "pub"
    // ...
    }
    return fmt.Sprintf("unknown protocol number %d", p)
}
```

_Key points/advantages_:
* `ProtocolName(number uint16)` would no longer be needed, using `%d` for protocol number, `%s` for the corresponding name;
* the `Protocol.Number() uint16` would change to return a `ProtocolNumber`;
* thus `Protocol.Name() string` would no longer be needed (`= Protocol.Number().String()`);
* a `ParseProtocolName(s string) ProtocolNumber` could perform the inverse and return a `ProtocolNumber`, or `error` on failure.*

**Comment by gdamore** [comment]
Seems reasonable.  Doubt it would do much for improving performance or anything, and probably little change to legibility, but it would be more "idiomatic" I think.  One question is whether the case statement or map lookup is faster.  Probably the case statement in this situations is slightly faster, because we don't have many protocols to sort from.

**Comment by gdamore** [comment]
I need to think on this -- my biggest concern about the PR you submitted is to make sure that the changes to API are not breaking for existing applications.  There are a lot of folks using mangos now, and I don't want to break any of them. :-)

**Comment by grrtrr** [comment]
The only outward visible change is the removal of the `.Name()` method, since `ProtocolNumber` now has its own `String()` method. Re-introduce the `Name()` method?

**Comment by grrtrr** [comment]
Thanks. I will resubmit this with a changed `Name()` method later, and instead generate a PR for the `macat` fix.
