### ISSUE TITLE
macat: tcp+tls complains about missing TLS configuration

### ISSUE THREAD

**Issue by grrtrr** [go-mangos/mangos#204]
When using `macat` with `tls+tcp` and `--cert/--key`, the listening side fails with 
```
Bind(tls+tcp://127.0.0.1:8080): missing TLS configuration
```
The _connecting side_ just hangs. The _reason_ is that the  TLS configuration is passed via `sock.SetOption`; it should have been a `DialOption` or `ListenOption`:
```go
sock.SetOption(mangos.OptionTLSConfig, &tlscfg)
```
The above call produces `ErrBadOption`, but is not caught.

**Comment by gdamore** [comment]
This is a regression that was introduced with 3c7e667c50982ad31c39ecbc4c6537cb3e963097

We should just use DialOptions() and ListenOptions if we have a tls config.

**Comment by grrtrr** [comment]
I have a local fix for this, will submit this for review.

**Comment by gdamore** [comment]
Cool.  Was going to fix myself but this will save me effort. :) thanks.
