### ISSUE TITLE
PubSub not working with remote subscriber

### ISSUE THREAD

**Issue by pebbe** [go-mangos/mangos#214]
I have a pub+sub implemented in ZeroMQ.

The publisher is on machine A, the subscriber on machine B.
In the publisher I use this address: `tcp://*:44557`
In the subscriber I use:  `tcp://`remote-hostname`:44557`

Machine B receives messages from machine A.

I tried to do the same with mangos.

In the publisher, an address with a `*` doesn't work. I tried these instead: `tcp://127.0.0.1:44557` and `tcp://localhost:44557`

In the subsciber I use the same address as in the ZeroMQ version.

I can subscribe locally, from machine A, but not from machine B.
On machine B, I get no errors, but no messages either.

Am I doing something wrong?

**Comment by gdamore** [comment]
you can use 0.0.0.0 or omit the hostname. Using only local host on the publisher means that only subscribers on the same host will work.

**Comment by pebbe** [comment]
OK, that works, mostly. But sometimes, when there is no subscriber, the publisher blocks. That is not desirable. I think I'll stick with ZeroMQ for the moment, and give mangos another try in a year or so.

**Comment by gdamore** [comment]
It would be useful to have a test case demonstrating that the publisher blocks.  That should not occur.

**Comment by gdamore** [comment]
Ok, I've got a repro for this; stay tuned.

**Comment by gdamore** [comment]
I've fixed the blocking issue and added a test for it.  Thanks for reporting that problem.

**Comment by gdamore** [comment]
With #222 I've added support for the wild card, and your other problems are now fixed.  Closing this report.
