### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by churchilllake** [go-mangos/mangos#216]
I want to point out a problem I'm having.  I've reproduced it in macat.  I'm PUBing a 4.3M message, over TCP, node to node.  I'm getting a panic from go-mangos as called by my go program.  I tried to SUB the message in macat and get the exact same problem.  I've included a delve debugging log below showing a trail.  I'd have expected sz to have been the 4.3M number, not 939099.  But the binary.Read that retrieved the number got it from the network socket.

Guessing 939099 is but a little short of the 1M mark, maybe there's a MaxRecvSize issue? I gave macat a --maxrecvsize flag and reran it.  After confirming the setOption succeeded, I got the same panic with the same values.  I think I put the setOption in the right place and can provide my changes if that is helpful to see where it is.

Guessing maybe this is a golang issue I make this program:

```
package main
import "fmt"

func main() {
	var a []byte
	b := a[0:939099]
	fmt.Printf("len of b = %v, cap of b = %v\n", len(b), cap(b))
}
```
I get the same panic (line 60 below) from the line before the print.  As I see it, your intent is to size the slice to accept the message, instead of growing it dynamically.  Am I right?  I don't know what to do with this information but to ask you what to do next?  Is 939099 a ligit value even?  It's big but only to someone programming on a 16 bit computer.

```
p and n are dlv print and next commands.

(dlv) p msg
*struct github.com/go-mangos/mangos.Message nil
(dlv) p sz
939099
(dlv) n
> github.com/go-mangos/mangos.(*conn).Recv() /Users/robbin/Projects/CHLMon/src/github.com/go-mangos/mangos/conn.go:60
    55:		// unlimited.  This avoids a potential denaial of service.
    56:		if sz < 0 || (p.maxrx > 0 && sz > p.maxrx) {
    57:			return nil, ErrTooLong
    58:		}
    59:		msg = NewMessage(int(sz))
=>  60:		msg.Body = msg.Body[0:sz]
    61:		if _, err = io.ReadFull(p.c, msg.Body); err != nil {
    62:			msg.Free()
    63:			return nil, err
    64:		}
    65:		return msg, nil
(dlv) p msg
*struct github.com/go-mangos/mangos.Message {
	Header: []uint8 len: 0, cap: 32, [],
	Body: []uint8 len: 0, cap: 64, [],
	Port: github.com/go-mangos/mangos.Port nil,
	bbuf: []uint8 len: 0, cap: 64, [],
	hbuf: []uint8 len: 0, cap: 32, [],
	bsize: 64,
	refcnt: 1,
	expire: time.Time {
		sec: 0,
		nsec: 0,
		loc: *struct time.Location nil,
	},
	pool: *sync.Pool nil,
}
(dlv) n
panic: runtime error: slice bounds out of range

goroutine 18 [running]:
panic(0x3959c0, 0xc82000e080)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/go-mangos/mangos.(*conn).Recv(0xc8200ee000, 0x412700, 0x0, 0x0)
	/Users/robbin/Projects/CHLMon/src/github.com/go-mangos/mangos/conn.go:60 +0x2f1
github.com/go-mangos/mangos.(*pipe).RecvMsg(0xc8200ee050, 0xc820060300)
	/Users/robbin/Projects/CHLMon/src/github.com/go-mangos/mangos/pipe.go:109 +0x41
github.com/go-mangos/mangos/protocol/sub.(*sub).receiver(0xc8200104c0, 0xf51190, 0xc8200ee050)
	/Users/robbin/Projects/CHLMon/src/github.com/go-mangos/mangos/protocol/sub/sub.go:52 +0xbb
created by github.com/go-mangos/mangos/protocol/sub.(*sub).AddEndpoint
	/Users/robbin/Projects/CHLMon/src/github.com/go-mangos/mangos/protocol/sub/sub.go:100 +0x49
Process 59519 has exited with status 2
(dlv) 
```

**Comment by churchilllake** [comment]
ps, **p msg**,**p sz** & **n** are really "p msg", "p sz" and "n", the github web formatter substituted bolding with "**".  p and n being dlv print and next.

**Comment by gdamore** [comment]
I think this is the known regression. go back a couple of commits.  I will push a fix tonight.

**Comment by churchilllake** [comment]
I changed line 60 to:
`msg.Body = make([]byte,sz)`
and it works now.

**Comment by gdamore** [comment]
Can you please make sure your version of mangos is up-to-date.  I believe you were hitting a problem described in #213  the fix for which was integrated last week.  Let me know if that solves it for you?

**Comment by churchilllake** [comment]
It worked fine and my solution would have leaked memory like a seive
.

**Comment by gdamore** [comment]
That's great news.  Closing.
