### ISSUE TITLE
lost msg in bus model

### ISSUE THREAD

**Issue by chowyu08** [go-mangos/mangos#228]
SEND CODE
for i := 0; i < 10000; i++ {
		bus.Send([]byte("HELLO"))
		// time.Sleep(time.Microsecond * 10)
		fmt.Println(i)
}
if I do not add the time.sleep(); the receiver will lost message, the sleep time at least 10 ms？
why?

**Comment by lthibault** [comment]
Could this be related to #230 ?

**Comment by gdamore** [comment]
This pattern is best effort and there is no backpressure exerted. So if you send faster than the receiver can receive, we have no choice but to drop messages. This is just like UDP.
