### ISSUE TITLE
gopkg.in import broken.

### ISSUE THREAD

**Issue by binary132** [go-mangos/mangos#229]
`go get -u -v gopkg.in/mangos.v1`

> package gopkg.in/mangos.v1: code in directory <$GOPATH>/src/gopkg.in/mangos.v1 expects import "github.com/go-mangos/mangos"

**Comment by binary132** [comment]
fwiw, this is why I have elected not to use gopkg.in for some projects -- you have to either use it all the way, or not use it.  I haven't seen a way around this.

**Comment by gdamore** [comment]
Maybe I should abandon gopkg.in -- I'm not too thrilled with it at the moment.

**Comment by binary132** [comment]
gopkg is a fully locked-in solution which doesn't offer real utility, compared to git tag semantic versioning.  It does cause inconsistent builds, however, since the only guarantee is major version.  i.e., two people can `go get gopkg.in/mangos.v1` and have two different versions, with different bugfixes and APIs.

Tragedy of the commons....

**Comment by gdamore** [comment]
It seems that my use of a canonical path in doc.go is the source of problems here, and makes mangos incompatible with gopkg.in.  I'm not entirely sure what the best option here is.

**Comment by gdamore** [comment]
I'm removing the canonical import path for now.

In the future I have plans to move this repo, possibly off of github, and we will probably host it under a nanomsg URL.  But that will signal a 2.0 version, which will have other major changes.
