### ISSUE TITLE
Only one Dialer receives messages from STAR pattern

### ISSUE THREAD

**Issue by lthibault** [go-mangos/mangos#230]
When running the code below, the only output is the following:

```
2016/10/12 02:23:40 READY
2016/10/12 02:23:40 [ S1 ] HELLO WORLD
```

Based on the documentation, which states that 

>that the messages are delivered not just to immediate peers, but to all members of the topology

I expected something like following output:

```
2016/10/12 02:23:40 READY
2016/10/12 02:23:40 [ S2 ] HELLO WORLD
2016/10/12 02:23:40 [ S1 ] HELLO WORLD
```

## What am I doing incorrectly?  Is this a bug?

```
package main

import (
	"log"
	"time"

	"github.com/go-mangos/mangos"
	"github.com/go-mangos/mangos/protocol/star"
	"github.com/go-mangos/mangos/transport/inproc"
)

var (
	err            error
	master, s1, s2 mangos.Socket
)

func init() {
	if master, err = star.NewSocket(); err != nil {
		log.Fatal(err)
	}

	if s1, err = star.NewSocket(); err != nil {
		log.Fatal(err)
	}

	if s2, err = star.NewSocket(); err != nil {
		log.Fatal(err)
	}

	master.AddTransport(inproc.NewTransport())
	s1.AddTransport(inproc.NewTransport())
	s2.AddTransport(inproc.NewTransport())

	if err = master.Listen("inproc:///"); err != nil {
		log.Fatalf("error in listening (master): %s", err)
	}

	if err = s1.Dial("inproc:///"); err != nil {
		log.Fatal(err)
	}

	if err = s2.Dial("inproc:///"); err != nil {
		log.Fatal(err)
	}

	log.Println("READY")
}

func main() {
	if err = master.Send([]byte("HELLO WORLD")); err != nil {
		log.Fatal(err)
	}

	go func() {
		for {
			msg, e := s1.Recv()
			if e != nil {
				log.Printf("[ ERR S1] %s", err)
			} else {
				log.Printf("[ S1 ] %s", string(msg))
			}
		}
	}()

	go func() {
		for {
			msg, e := s2.Recv()
			if e != nil {
				log.Printf("[ ERR S1] %s", err)
			} else {
				log.Printf("[ S2 ] %s", string(msg))
			}
		}
	}()

	<-time.After(15 * time.Second)
}
```

Many thanks in advance!

**Comment by gdamore** [comment]
looks like a bug indeed.  stay tuned.  (does tcp suffer the same problem?)

**Comment by lthibault** [comment]
I will check tcp ASAP.  In the meantime, I get similar behaviour with the `bus` protocol.

**Comment by lthibault** [comment]
A few updates:

**Firstly** the bug appears to be stochastic in nature.  I ran the above code on my work computer and I get the following outputs seemingly at random:

- No output (other than `READY`)
- `S1` log message *only*
- `S1` && `S2` log messages (rare)

A bit of terminal output to demonstrate

```
$ go run main.go
2016/10/12 16:41:44 READY
2016/10/12 16:41:44 [ S1 ] HELLO WORLD
2016/10/12 16:41:44 [ S2 ] HELLO WORLD

$ go run main.go
2016/10/12 16:42:04 READY

$ go run main.go
2016/10/12 16:44:26 READY

$ go run main.go
2016/10/12 16:45:00 READY
2016/10/12 16:45:00 [ S1 ] HELLO WORLD
```

**Secondly**, the above behaviour also occurs using the BUS protocol as well.

**Third**, when using TCP (for both STAR and BUS), the only behaviour I observe is **no output**.

For the purposes of sanity-check, I defined my TCP sockets as follows:

```
    if err = master.Listen("tcp://localhost:9000"); err != nil {
        log.Fatalf("error in listening (master): %s", err)
    }

    if err = s1.Dial("tcp://localhost:9000"); err != nil {
        log.Fatal(err)
    }

    if err = s2.Dial("tcp://localhost:9000"); err != nil {
        log.Fatal(err)
    }
```

Any ideas?

Louis

**Comment by gdamore** [comment]
Ok, I've looked at this, and the problem is that Dial() is occurring asynchronously (by design), so you can have a situation where you wind up calling Send() before the Dial() completes.  Whether this happens or not is entirely dependent on the scheduler, and can change.

In order to solve this problem, you need to not assume that Dial() returning indicates that a connection is established.  (Underlying connections can come and go... Dial just sets up the "logical" connection.)

As a workaround, you can try adding a time.Sleep(time.Second) (or some smaller increment) at the start of main().  (Because init() runs immediately before main().)  If I do that, then your example completes  successfully every time.

**Comment by lthibault** [comment]
Thanks for the detective work!  Should I make this same assumption for _all_ sockets, regardless of protocol?  Are all protocols "best-effort" or do some (most?) have stronger guarantees?

Thanks again!

**Comment by gdamore** [comment]
Yes.  With the exception of Req/Rep, which has an implied retry.  (Though it can take it a while before it decides to retry your message.)
