### ISSUE TITLE
Data race in surveyor Recv during Init

### ISSUE THREAD

**Issue by binary132** [go-mangos/mangos#236]
Immediately after dialing 3 listening inproc Respondents, I call Send on my Surveyor socket, and then immediately call Recv.  Testing with -race:

```
$ go test -race -check.f TestNewResp
==================
WARNING: DATA RACE
Write at 0x00c420072950 by goroutine 36:
  github.com/synapse-garden/sg-proto/vendor/github.com/go-mangos/mangos.(*socket).SetRecvError()
      /Users/jsolomon/meta/dev/go/src/github.com/synapse-garden/sg-proto/vendor/github.com/go-mangos/mangos/core.go:167 +0x59
  github.com/synapse-garden/sg-proto/vendor/github.com/go-mangos/mangos/protocol/surveyor.(*surveyor).Init.func1()
      /Users/jsolomon/meta/dev/go/src/github.com/synapse-garden/sg-proto/vendor/github.com/go-mangos/mangos/protocol/surveyor/surveyor.go:56 +0x8b

Previous read at 0x00c420072950 by goroutine 8:
  github.com/synapse-garden/sg-proto/vendor/github.com/go-mangos/mangos.(*socket).RecvMsg()
      /Users/jsolomon/meta/dev/go/src/github.com/synapse-garden/sg-proto/vendor/github.com/go-mangos/mangos/core.go:264 +0xf6
  github.com/synapse-garden/sg-proto/vendor/github.com/go-mangos/mangos.(*socket).Recv()
      /Users/jsolomon/meta/dev/go/src/github.com/synapse-garden/sg-proto/vendor/github.com/go-mangos/mangos/core.go:287 +0x50
```

**Comment by binary132** [comment]
(The reason I was running race tests is that I am randomly getting ErrProtoState on Recv.  This problem goes away when I add a short sleep between my Dial and my Send / Recv.  It is also minimized but not fully eliminated using runtime.Gosched() instead.)

**Comment by gdamore** [comment]
Thanks.   I will investigate.

**Comment by binary132** [comment]
Fwiw, the vendored ref is https://github.com/go-mangos/mangos/commit/c3916ba23b3aa721fd13b4dec916b2d15f4a2520.

**Comment by binary132** [comment]
I'll whip up a simplified reproduceable demo tonight if needed.

**Comment by gdamore** [comment]
Yep, its a clear race.  Relatively easy to fix.  Do you have a test case for it?

**Comment by gdamore** [comment]
I don't need the demo, but a test case we can integrate into the test suite would be nice.

**Comment by binary132** [comment]
I am not actually clear on what is causing the race so writing a test to demonstrate it will be "hard" :P

**Comment by gdamore** [comment]
Fair enough -- if you could post your test program that would still be helpful.

That said, the race is caused by the attempt to access the Socket's recverr member without holding the Socket.Lock.

Reviewing the logic there last night, I found it to be a bit more convoluted than I'd like.  I will try to fix it later today.  (A quick fix will not be difficult.  Changing the logic to be a bit more straight-forward will take a little longer.)

**Comment by binary132** [comment]
`go run -race`

https://play.golang.org/p/VubnL5qoIx
