### ISSUE TITLE
Reconnect issue

### ISSUE THREAD

**Issue by NikSmith** [go-mangos/mangos#251]
Hello, I have problem when instance lose net connection.
If we run two instance and blocking port for one and after unblock port, than instance not recovery connection to another instance. How I can resolve this problem?

**Comment by gdamore** [comment]
can you provide any more detail?  mangos should automatically retry (it might take a while though.  I have to look at the code to remind myself about the reconnect times.)

**Comment by NikSmith** [comment]
I'm sorry. It was bug in my code.

**Comment by gdamore** [comment]
Glad you figured it out.
