### ISSUE TITLE
Need example for using websockets & demuxing mangos sockets

### ISSUE THREAD

**Issue by omani** [go-mangos/mangos#254]
Hi,

first of all thank you for this awesome project.

I would like to know how I can use a pub/sub and a req/rep via a websocket endpoint and binding both services on the same port.

my intention is to have one common socket to make all my communications (different patterns) with.

any example are appreciated.

thanks

**Comment by gdamore** [comment]
To do this you need to create an HTTP server and use multiple sockets with it, using different paths on the server to identify the namespaces for different sockets (e.g. prefix/PUB  or prefix/SURVEYOR or some other string -- could be anything really).

Basically, what you do is use the OptionWebSocketMux on the listener, and then register that with a normal Http ServeMux.   This way you can use mangos even with lots of other middlewares.

I'll write an example.

**Comment by gdamore** [comment]
You can use that example code.  Note that you *must* also have the fix for #258 -- which I integrated just prior to this example, in order for the example code to function.

**Comment by omani** [comment]
this is awesome. thank you very much. I just tried it out. you must not specify the loopback address though. since you hardcoded tcp://127.0.0.1 already. so in main.go `url=tcp://127.0.0.1:40899` should be just `url=40899` for easy copy pasting.
