### ISSUE TITLE
Assure TLS handshake completes before storing state

### ISSUE THREAD

**Issue by blitzrk** [go-mangos/mangos#260]
In `tlstcp.go`, TLS connection state is stored at line 91 and 159 for dial and listen respectively. The latter assures that a handshake has completed so the `tls.ConnectionState` object is fully populated. Because it's missing at line 90, I'm encountering a race condition of the connection state sometimes containing certificates and sometimes being empty.

**Comment by gdamore** [comment]
Hmm... you didn't make the above a PR, did you mean to?
