### ISSUE TITLE
Websocket client authentication via cookies?

### ISSUE THREAD

**Issue by nsjph** [go-mangos/mangos#266]
I'd like to authenticate client connections, similar to this request: [Gorilla Issue 151 - How to authentication client connection ](https://github.com/gorilla/websocket/issues/151) 

Would the following suggestion be possible with mangos/transport/ws? 

`I recommend authenticating the upgrade handshake using the application's code for authenticating HTTP requests.`

**Comment by omani** [comment]
I am using json webtokens (JWT) for client authentication. If you are interested I can give you some code snippets.

**Comment by nsjph** [comment]
If you could share some example code, that would be appreciated.

My initial thought is to send a JSON-encoded Request struct which 
include a cookie, generated separately. This can then be validated 
server-side. For example:

type ClientRequest struct {

     Name string

     Args map[string]string

     Cookie string

}

**Comment by gdamore** [comment]
I believe it should be possible to do this.  That said, I've no time to work on it at present.  Let me know if you need assistance -- but I think the idea is that you can access the headers and then make decisions in your application by looking at the websocket headers.  I certainly don't want to have mangos doing any authentication on its own -- that would be an architectural mistake.

I'm closing this for now, but feel free to reopen with further explanation or questions and I will try to find time to work with you to resolve any issues.
