### ISSUE TITLE
Alias to io.Writer io.Reader  Interface?

### ISSUE THREAD

**Issue by mengzhuo** [go-mangos/mangos#268]
I think it would be more convenience for other developer that we alias Send([]byte)/ Recv([]byte) to io.Write and io.Read interface.

For example:
```go
sock , err := pub.NewSocket()
io.Copy(sock, src) # you can't do this

# instead, I had to wrap mangos Socket into writer
type writer struct {
     sock mango.Socket
}

func (w *writer) Write(p []byte) (n int, err error) {
   err = w.sock.Send(p)
   return len(p), err
}
```

**Comment by gdamore** [comment]
This is a really bad idea. The mangos API and the underlying protocols are message oriented but the io APIs are for stream oriented io.  This difference is super fundamental and you cannot generally substitute one for the other.
