### ISSUE TITLE
Channel-based message cache vs sync.Pool

### ISSUE THREAD

**Issue by tylertreat** [go-mangos/mangos#27]
It looks like GC is minimized by using a message cache so messages are reused (https://github.com/gdamore/mangos/blob/master/message.go#L41). This is currently implemented using channels to provide a buffer of disposed messages. My experience has been that channels are generally slowish. I'm curious if a decision was consciously made to _not_ use a [sync.Pool](http://golang.org/pkg/sync/#Pool)? I'd be interested to see benchmarks for both.

**Comment by isayme** [comment]
for someone new here: sync.Pool used by Message with issue #33.
