### ISSUE TITLE
Add to pub sub example...

### ISSUE THREAD

**Issue by Ranx0r0x** [go-mangos/mangos#272]
I've started working with the Mango library and like it quite a bit and hope to do some further work with it.  The examples are good but spartan. I think in some cases small tweaks to the code samples will help a lot.  For example, it didn't take long to figure out since I've worked with pub/sub messaging but the following works to demonstrated.

Instead of the server just sending a byte array to everyone this simple modification shows how to send to subscribers on a topic which is usually what one is after, this is the message being sent to a "dateTopic".  The client code is modified 

SERVER
for {
		d := date()
		fmt.Printf("SERVER: PUBLISHING DATE %s\n", d)
		header:=[]byte("dateTopic")
		body:=[]byte(d)
		msg:=mangos.Message{Header:header,Body:body}
		if err = sock.SendMsg(&msg); err != nil {

CLIENT
func client(url string, name string, topic string) {
...
// Empty byte array effectively subscribes to everything
	err = sock.SetOption(mangos.OptionSubscribe, []byte(topic))

And the shell script.  When the script is run it shows the client 0 and 1 received date and client2 does not since it is registered on a "fooTopic"

./localbus client $url client0 dateTopic & client0=$!
./localbus client $url client1 dateTopic & client1=$!
./localbus client $url client2 fooTopic & client2=$!

**Comment by gdamore** [comment]
So the problem is that your use of Header is incorrect.  The subscription is intended to match against the payload; PUB/SUB does not have a protocol-specific header.  (That is, the "topic" is not a separate field in some protocol header.)

The code you've supplied works "by accident" because we simply concatenate the Header and the Body together on the wire.  But its absolutely the wrong approach to use.

**Comment by porjo** [comment]
I've just started using Mangos and found myself wondering how to specify the topic when publishing. I went to the Nanomsg docs to understand how this works. I think the Mangos examples could be updated to make this clearer for newcomers.
