### ISSUE TITLE
Not working with Message.Header

### ISSUE THREAD

**Issue by eberkund** [go-mangos/mangos#274]
I modified the example in `examples/reqrep/reqrep.go` to use `RecvMsg` and `SendMsg` instead of `Send` and `Recv` and it doesn't work. It seems to work fine as long as I do not attempt to set the header to a non-empty value on the request.

	msg = mangos.NewMessage(32)
	msg.Body = []byte("HELLO")
	msg.Header = []byte("TEST")

	if err = sock.SendMsg(msg); err != nil {
		die("can't send message on push socket: %s", err.Error())
	}

**Comment by gdamore** [comment]
The "Header" is not for arbitrary use.  Instead, the individual protocols use (some do, some don't) the Header for protocol specific purposes; the only valid use by applications of the Header is to populate data there that represents the SP-protocol headers when you have set the OptionRaw option to true.  This should only rarely be needed, and only for applications that need to have more fine grained control over the inner workings of protocols or need to implement concurrent asynchronous servers (that is servers that support processing multiple overlapping requests at the same time).

**Comment by gdamore** [comment]
Arguably the restrictions around the Header field should be better documented, so I'm leaving this open as a "documentation request".

**Comment by eberkund** [comment]
I read somewhere in the comments that the header is useful for raw sockets and assumed I could make use of them for other types too. Thank you for the clarification.
