### ISSUE TITLE
IPC on windows?

### ISSUE THREAD

**Issue by johndrummond** [go-mangos/mangos#279]
Hi,
on the readme you have
Note that ipc:// is not supported on Windows (by either this or the reference implementation.)
but http://nanomsg.org/v1.0.0/nn_ipc.7.html
has
On Windows, named pipes are used for IPC

Are there any plans to add IPC in the same way? 
Thanks for the library and work on resuscitating Nanomsg.
Kind regards, John.

**Comment by gdamore** [comment]
Yes at some point I would like to get back to that.

**Comment by gdamore** [comment]
This is a dup of #2
