### ISSUE TITLE
Dropped packets when using Pub/Sub

### ISSUE THREAD

**Issue by nikhotine** [go-mangos/mangos#280]
Hi.

The pub/sub protocol seems to drop packets in a tight loop. I modified the `/examples/pubsub/pubsub.go` to send few messages in a for loop and then sleep for a while before sending again.
Example:
```
...
for i := 1; i <= 250; i++ {
	if err = sock.Send([]byte(d)); err != nil {
		die("Failed publishing: %s", err.Error())
	}

        count++
	
}
fmt.Println("Sent 250 messages")
time.Sleep(time.Millisecond * 500)
...
``` 
I observed that the above code causes the client to drop many packets.
```
Server		Client 1		Client 2
---------------------------------------------------------
1750		788				788
6500		3802			3841
14250		8890			9148
30000		18355			18406
53500		32466			32144
```
As you can see, the client ended up dropping around 40% of the packets sent. The client in this case does no processing on the packet.(only increments a counter).

However adding a small delay in the tight loop seems to solve the issue.
```
...
for i := 1; i <= 250; i++ {
	if err = sock.Send([]byte(d)); err != nil {
		die("Failed publishing: %s", err.Error())
	}

        count++
        time.Sleep(time.Millisecond * 1)
	
}
fmt.Println("Sent 250 messages")
...
```
In the above case, the client received every packet sent by the server.

Any idea as to what is causing this issue?

**Comment by gdamore** [comment]
The pub sub protocol is best effort (any multicast must be). As a result if
the sender sends data faster than the receiver can process them the
messages will be dropped. This is intrinsic. Slowing down the sender lets
the receiver catch up which is why that works. Real world applications
should not be blasting messages as hard as they can with this protocol.

**Comment by nikhotine** [comment]
Thanks for the clarification. I'll close this.
