### ISSUE TITLE
message not delivered when publishing only 1 message and closing the socket.

### ISSUE THREAD

**Issue by edwardborst** [go-mangos/mangos#281]
I'm using pub / sub.
I have a publisher connecting to an url.
When I send a message and close the socket it is not delivered.
How to clean shutdown (and deliver the message) the socket?
In the example pub/sub there is a for loop.
after the second message is sent the first is delivered. 
when closing the socket the last message is lost.

**Comment by gdamore** [comment]
Because the delivery is asynchronous if you close the socket the message
can be lost. There is some attempt to prevent that with the linger option,
but it does not work everywhere.

If your application sleeps for a bit (100ms is generally adequate) before
closing, it should be sufficient. l

**Comment by edwardborst** [comment]
I have tried that already. no luck so far.
with nanomsg (nodejs) I had to shutdown the port instead of close. this forced the port to cleanly shutdown.
with mangos i couldn't find the shutdown...

This is my code so far:

`func publish(url string, msg string) {
	if sock, err = pub.NewSocket(); err != nil {
		die("can't get new pub socket: %s", err)
	}
	sock.SetOption(mangos.OptionLinger, time.Second)
	sock.SetOption(mangos.OptionNoDelay, true)
	// sock.SetOption(mangos.OptionWriteQLen, 0)
	// sock.AddTransport(ipc.NewTransport())
	sock.AddTransport(tcp.NewTransport())
	if err = sock.Dial(url); err != nil {
		die("can't connect on pub socket: %s", err.Error())
	}
	log.Println("Publishing: ", msg)
	if err = sock.Send([]byte(msg)); err != nil {
		die("Failed publishing: %s", err.Error())
	}
}

func main() {

	msg := "{ The message....  }"
	addr := "tcp://127.0.0.1:3000"
	publish(addr, msg)
	time.Sleep(time.Second)
	sock.Close()
}
`

**Comment by edwardborst** [comment]
it seems the issue is in sending the message direct after connecting.
when I sleep 1 second before sending  the message it is going fine.
Is the sock.Dial async as well?

**Comment by gdamore** [comment]
Yes, sock.Dial is asynch.  You should wait a little bit.  100 msec is plenty for most uses.

**Comment by gdamore** [comment]
I should look at options to make sock.Dial synch.  Recently, we've decided/discovered that the asynch dial for the *first* dial attempt is the source of much confusion and many problem reports.

I need to think how best to align mangos to the current thinking.

**Comment by gdamore** [comment]
I will file another issue about that.  Closing this one.
