### ISSUE TITLE
The REQ does not support connect to multiple REP？

### ISSUE THREAD

**Issue by wllenyj** [go-mangos/mangos#289]
nanomsg can do this, like:
``` c
req = nn_socket (AF_SP, NN_REQ);

nn_connect (req, "tcp://srv1");
nn_connect (req, "tcp://srv2");
nn_connect (req, "tcp://srv3");
```
I need to use mangos to implemente Load balancing, but seems impossible.
How to do？
Thanks.

**Comment by gdamore** [comment]
Should just work.  You can just do Dial() to each of those different addresses.  If it doesn't work for some reason please provide details.

**Comment by wllenyj** [comment]
oh, I 'm sorry, my mistake.
Thank you.
