### ISSUE TITLE
TestScalability: panic: send on closed channel

### ISSUE THREAD

**Issue by glycerine** [go-mangos/mangos#296]
At latest, 2645a781e132c8f63127f0ec64318477a4dd913b

~~~
=== RUN   TestScalability
panic: send on closed channel

goroutine 1115 [running]:
github.com/go-mangos/mangos/protocol/rep.(*rep).sender(0xc420356160)
        /Users/jaten/go/src/github.com/go-mangos/mangos/protocol/rep/rep.go:168 +0x246
created by github.com/go-mangos/mangos/protocol/rep.(*rep).Init
        /Users/jaten/go/src/github.com/go-mangos/mangos/protocol/rep/rep.go:56 +0x17c
exit status 2
FAIL    github.com/go-mangos/mangos/test        78.160s
jaten@jatens-MacBook-Pro ~/go/src/github.com/go-mangos/mangos/test (master) $ 
~~~

**Comment by glycerine** [comment]
its not deterministic, my 2nd and 3rd test runs passed.

**Comment by glycerine** [comment]
go version go1.9 darwin/amd64

**Comment by gdamore** [comment]
I suspect that the req/rep retry stuff introduced a race.  Will investigate.

**Comment by gdamore** [comment]
This does *not* look like it was introduced by 286.  I think it is an entirely separate issue.

**Comment by gdamore** [comment]
So this was a close race (definitely not related to #298).  Very unlikely, but possible.  The more I interact with go channels, the less and less I like them.  The fact that we have no way to cleanly shutdown / wait for go routines makes cleaning up after them a pain.

Arguably I could just not close the channel at all, and leave it for garbage collection.  A better solution, IMO, is to extend the lock to cover the removal, which should fix this race for now.  (I'm pretty sure the drain logic in shutdown means this only happens on peer disconnect, not on complete socket shutdown.)

**Comment by glycerine** [comment]
Yes. Channels were a rather rushed design. Not allowing more than one close for example, in my experience was a design mistake (so I use my idem library frequently[1]). Also no way to easily model latches[2], and sticky channels[3] would be a big improvement. I've proposed fixes (and provided prototype libs) but very little interest out there, even for backwards compatable changes.

[1] https://github.com/glycerine/idem/blob/master/halter.go#L8 This is my approach to clean shutdown of go routines: all go routines have a corresponding struct that contains an idem.Halter. Anybody can call RequestStop on the Halter at any point. When the go routine notices the halt request, it stops itself, doing a halter.MarkDone() as its last action before returning.  I also have code that maintains a network of depedent parent/child goroutines, and is able to shutdown the entire network cleanly using this system, but that is rather advanced (I can provide pointers if interested).

[2] https://github.com/glycerine/latch and https://github.com/golang/go/issues/18951

[3] see my comment on https://github.com/golang/go/issues/21165; quoting the relevant parts: 

> A2) a more general approach would be to allow the sending of values tagged as "sticky", and let sticky values be consumed an infinite number of times. This could be nice if you want the buffer of the channel to contain both sticky and non-sticky values. You would need a new operation to consume and eliminate a sticky value.
>
> ...
> edit: A2 may have the advantage of being the most backwards compatible, and the advantage of having obviously novel syntax for sending sticky values. Suppose for instance that the operator <~ was chosen for sticky send. Example ch := make(chan int); ch <~ 1; would send the value 1 as a sticky value, that could be received many times. The new syntax would make the use of the sticky value very visually distinct.
