### ISSUE TITLE
new release? 1.2 is over a year old, almost 2.

### ISSUE THREAD

**Issue by james-lawrence** [go-mangos/mangos#314]

**Comment by gdamore** [comment]
Good point -- its time.  We haven't made a lot of changes here (I've been focused on NNG -- the C version of this), but a few of them are probably worthy at least of cutting 1.3.

**Comment by gdamore** [comment]
I've got some stuff I'm going to integrate first... a commercial sponsor has stepped up to request IPC support at least.

**Comment by gdamore** [comment]
v1.3.0 is tagged now.
