### ISSUE TITLE
question

### ISSUE THREAD

**Issue by falafflepotatoe** [go-mangos/mangos#39]
Hi - noob here. I guess I fail to understand the paradigm and dont see it in the docs - are we locked into the pattern we choose or can we mix and match features? Ie pair with broadcast?

Does pair only work with pair? And pub only with sub? or can I mix Sub to pair? Its unclear to muh noobness what the paradigm is here.

I'm trying to do a pair dialer client and pair server. Do I have to free_msg like in nano msg to get the next message? I dont see that in the docs... Im not getting the Second msg to my "server" socket - and writes are not going out either.  Do I have to respond before I can get the 2nd msg?

Also +1 for an example of a server / client that writes arbitrary msgs instead of one write and exit; the extra go boiler plate for wrapping the read/writes to chans/funcs is a bit confusing.

Thanks

**Comment by falafflepotatoe** [comment]
is it possible to get the IP sending a msg? / how can i do that?

**Comment by tylertreat** [comment]
So I actually hacked this into a fork which adds the remote address onto the `Message`: https://github.com/tylertreat-wf/mangos/pull/1/files.

I decided against making a PR upstream, although this will work for every transport besides inproc, which obviously remote addr doesn't apply.

**Comment by gdamore** [comment]
Actually this has broader benefits for some transports. Being able to provide more than just address -for example peer credentials for IPC or certificate info for TLS may allow transport validation to be used by upper protocols.  

That said I want to think very carefully about this.   Passing this info per message is clearly the right approach given that multiple transports may be involved and the disconnect between transports and messages. 

Stay tuned.  This also clearly is something that nanomsg itself lacks.

**Comment by falafflepotatoe** [comment]
thanks guys.  i have one more question: how can i tell if my dial sock is currently connected or if its in a dial state

**Comment by gdamore** [comment]
There isn't an API for that.  The state is "dynamic" really, since there can be multiple transports plumbed underneath a single socket.  When I need to track this in my apps, I do it in a boolean outside of the socket.  That said, we could add a "count" of number of notionally connected end points.  (Notional, because we'd count end points regardless of actual lower level transport state -- whether an actual TCP connection is present or not.  Dial() would bump the count even before the connection is complete.  Actually we could count both Dials and Listens as the count of the pipes[] and accepters[] arrays in struct socket.)

I'm not sure if this answers it for you or not.  If there is a need for this API, it wouldn't be hard to add it.

**Comment by gdamore** [comment]
Actually, pipes is appended to only when an actual outbound connect is established.  And it is cleaned up upon disconnect.  We probably need to bump a dialers count.  Its even possible that we could have a separate dialers[] array with NewDialer getting stuck there. 

Actually, this could lead to a variant of Dial (and of Listen) that return the handles to the dialer and listen structures, allowing them to be individually closed or removed from the socket -- that might be useful.  (Today there is no way to remove a dialer or listener from a socket, once added.)

**Comment by tylertreat** [comment]
For what it's worth, I would find it useful to be able to remove dialers/listeners. This was actually something I've wondered about myself. I could see the "counts" API being useful too.

**Comment by falafflepotatoe** [comment]
thanks for the code i will try it out asap

@gdamore - can you give me a small example of how you do a boolean if connected or not?
